version: '3'
services:
  pronto:
    image: ghcr.io/schwad/pronto-action:1.5.1
    volumes:
      - .:/pronto
    entrypoint: ["pronto"]
    command: run -r rubocop

# Run the following command to run pronto locally
# > docker-compose -f docker-compose-pronto.yaml run --rm pronto
# > docker-compose -f docker-compose-pronto.yaml run --rm pronto run -r rubocop --staged
