name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: schwad/pronto-action-reek-fork@v1.5.2
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
